dist: trusty
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

script:
  - mkdir build && cd build
  - cmake .. -DCMAKE_CXX_COMPILER=g++-7
  - cmake --build . -- -j2

